# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/karti/Documents/ECE_385/Lab6/Lab6.srcs/sources_1/bd/mb_block/ip/mb_block_xbar_2/mb_block_xbar_2.xci
# IP: The module: 'mb_block_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karti/Documents/ECE_385/Lab6/Lab6.gen/sources_1/bd/mb_block/ip/mb_block_xbar_2/mb_block_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/karti/Documents/ECE_385/Lab6/Lab6.srcs/sources_1/bd/mb_block/ip/mb_block_xbar_2/mb_block_xbar_2.xci
# IP: The module: 'mb_block_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/karti/Documents/ECE_385/Lab6/Lab6.gen/sources_1/bd/mb_block/ip/mb_block_xbar_2/mb_block_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
